workspase/mysite/plant/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'plant'

urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('signup/', views.Create_account.as_view(), name='user_create'),
    path('top/', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    # path('user_create/', views.UserCreate.as_view(), name='user_create'),
    # path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    # path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workspase/mysite/plant/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Photo(models.Model):
    image = models.ImageField(upload_to='photos')
    # result = models.ImageField(upload_to='result_photos')
    title = models.CharField(max_length=150)
    # comment = models.TextField(blank=True)
    # created_at = models.DateTimeField(auto_now=True)
    def publish(self):
        self.published_date = timezone.now()
        self.save()
    def __str__(self):
        return self.title


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

workspase/mysite/plant/forms.py
from django import forms
from django.contrib.auth.forms import (UserCreationForm, AuthenticationForm)
from django.contrib.auth import get_user_model
from .models import Document

User = get_user_model()

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('description', 'document', )

class MyForm(forms.Form):
    text = forms.CharField(
        label='Image Name ',
        max_length=100,
        required=True,
        widget=forms.TextInput()
    )

class PhotoForm(forms.Form):
    image = forms.ImageField()
    # text = forms.CharField(
    #     label='Image Name ',
    #     max_length=100,
    #     required=True,
    #     widget=forms.TextInput()
    # )


class LoginForm(AuthenticationForm):
    """ログインフォーム"""
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       #htmlの表示を変更可能にします
       self.fields['username'].widget.attrs['class'] = 'form-control'
       self.fields['password'].widget.attrs['class'] = 'form-control'

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     for field in self.fields.values():
    #         field.widget.attrs['class'] = 'form-control'
    #         field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる


class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #htmlの表示を変更可能にします
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

    class Meta:
       model = User
       fields = ("username", "password1", "password2",)

    # class Meta:
    #     model = User
    #     fields = ('email',)
    # 
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     for field in self.fields.values():
    #         field.widget.attrs['class'] = 'form-control'
    # 
    # def clean_email(self):
    #     email = self.cleaned_data['email']
    #     User.objects.filter(email=email, is_active=False).delete()
    #     return email

                    

workspase/mysite/plant/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.auth import get_user_model, login, authenticate
# from django.contrib.auth import login, authenticate
from django.contrib.auth.views import (LoginView, LogoutView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import Http404, HttpResponseBadRequest
from django.template.loader import render_to_string
from django.views import generic
from . import forms, models, silhouette

User = get_user_model()    

def upload(request):
    obj = models.Document.objects.all()
    if request.method == 'POST':
        form = forms.DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/plant/upload')
    else:
        form = forms.DocumentForm()
        obj = models.Document.objects.all()

    return render(request, 'plant/upload.html', {
        'form': form,
         'obj': obj
    })

    
# def upload(request):
#     obj = models.Photo.objects.get(id=num)
# 
#     if request.method == 'GET':
#         input_path
#         return render(request, 'plant/upload.html', {
#             # 'form_txt': forms.MyForm(),
#             'form': forms.PhotoForm(),
#             'photos': models.Photo.objects.all(),
#         })
#     elif request.method == 'POST':                                                     
#         form = forms.PhotoForm(request.POST, request.FILES)
#         if not form.is_valid():
#             raise ValueError('invalid form')            
#         photo = models.Photo()        
#         photo.save()
# 
#         if 'button_gray' in request.POST:
#             gray(obj.photo.url)
#             obj.gray = "gallery/gray.jpg"
#             obj.save()
#             return redirect('/plant/upload', num)
#         # piyo = '1'
#         # piyo = silhouette.main(piyo)
#             # gray, hoge = silhouette.main(piyo)
#         # return redirect('/plant/upload')
#     params = {'data': obj}
#     return render(request, 'plant/upload.html', params)

def gray(url):

    path = settings.BASE_DIR + url

    print(path)
    img = cv2.imread(path)
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    output = settings.BASE_DIR + "/media/gallery/gray.jpg"
    cv2.imwrite(output, img_gray)


#アカウント作成
class Create_account(generic.CreateView):
    def post(self, request, *args, **kwargs):
        form = forms.UserCreateForm(data=request.POST)
        if form.is_valid():
            form.save()
            #フォームから'username'を読み取る
            username = form.cleaned_data.get('username')
            #フォームから'password1'を読み取る
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
        return render(request, 'plant/user_create.html', {'form': form,})

    def get(self, request, *args, **kwargs):
        form = forms.UserCreateForm(request.POST)
        return  render(request, 'plant/user_create.html', {'form': form,})

create_account = Create_account.as_view()

class Top(generic.TemplateView):
    template_name = 'plant/top.html'


class Login(LoginView):
    """ログインページ"""
    form_class = forms.LoginForm
    template_name = 'plant/login.html'
#     def post(self, request, *arg, **kwargs):
#         form = LoginForm(data=request.POST)
#         if form.is_valid():
#             username = form.cleaned_data.get('username')
#             user = User.objects.get(username=username)
#             login(request, user)
#             return redirect('/')
#         return render(request, 'login.html', {'form': form,})
# 
#     def get(self, request, *args, **kwargs):
#         form = LoginForm(request.POST)
#         return render(request, 'login.html', {'form': form,})
# 
# account_login = Account_login.as_view()    


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'plant/top.html'
# 
# 
# class UserCreate(generic.CreateView):
#     """ユーザー仮登録"""
#     template_name = 'plant/user_create.html'
#     form_class = forms.UserCreateForm
# 
#     def form_valid(self, form):
#         """仮登録と本登録用メールの発行."""
#         # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
#         # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
#         user = form.save(commit=False)
#         user.is_active = False
#         user.save()
# 
#         # アクティベーションURLの送付
#         current_site = get_current_site(self.request)
#         domain = current_site.domain
#         context = {
#             'protocol': self.request.scheme,
#             'domain': domain,
#             'token': dumps(user.pk),
#             'user': user,
#         }
# 
#         subject = render_to_string('plant/mail_template/create/subject.txt', context)
#         message = render_to_string('plant/mail_template/create/message.txt', context)
# 
#         user.email_user(subject, message)
#         return redirect('plant:user_create_done')


# class UserCreateDone(generic.TemplateView):
#     """ユーザー仮登録したよ"""
#     template_name = 'plant/user_create_done.html'
# 
# 
# class UserCreateComplete(generic.TemplateView):
#     """メール内URLアクセス後のユーザー本登録"""
#     template_name = 'plant/user_create_complete.html'
#     timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内
# 
#     # def get(self, request, **kwargs):
#     def post(self, request, *args, **kwargs):
#         """tokenが正しければ本登録."""
#         token = kwargs.get('token')
#         try:
#             user_pk = loads(token, max_age=self.timeout_seconds)
# 
#         # 期限切れ
#         except SignatureExpired:
#             return HttpResponseBadRequest()
# 
#         # tokenが間違っている
#         except BadSignature:
#             return HttpResponseBadRequest()
# 
#         # tokenは問題なし
#         else:
#             try:
#                 user = User.objects.get(pk=user_pk)
#             except User.DoesNotExist:
#                 return HttpResponseBadRequest()
#             else:
#                 if not user.is_active:
#                     # 問題なければ本登録とする
#                     user.is_active = True
#                     user.save()
#                     return super().get(request, **kwargs)
# 
#         return HttpResponseBadRequest()        

workspase/mysite/plant/templates/plant/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <!-- <title> login page </title> -->
</head>
<body>
    <!-- ナビバー -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'plant:top' %}"> My site </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li>
            <a class="nav-item nav-link" href="{% url 'plant:upload' %}">Uploader</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'plant:logout' %}">LOGOUT</a>            
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'plant:login' %}">
            Login
          </a>
          </li>
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'plant:user_create' %}">
            SignUp
          </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- メインコンテント -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

workspase/mysite/plant/templates/plant/login.html
{% extends "plant/base.html" %}

<p> Login page </p>

<body>
  {% block content %}  
  <div class="card col-md-6">
      <div class="card-body">
        {% if form.errors  %}
        <p>User name or Password is not correct.</p>
        {% endif %}
          <form method="POST" action="{% url 'plant:login' %}">
          {% csrf_token %}
          <label>User name</label> <br>        
          {{ form.username }}
          {{ form.username.errors }} <br>
          <label>Password</label> <br>
          {{ form.password }}
          {{ form.password.errors }} <br>
    <button type = "submit">LOGIN</button>
  </form>
  {% endblock %}      
</body>

workspase/mysite/plant/templates/plant/top.html
<!DOCTYPE html>
{% extends "plant/base.html" %}
<html lang="ja">
  <body>
    {% block content %}

    {% if user.id  %}
    <p>You're Logging in</p>
    <p>Namaste, {{ user.username }} :)</p>
    {% else %}
    <a href="{% url 'plant:login' %}">please LOGIN</a>
    {% endif %}

    {% endblock %}
  </body>
</html>

workspase/mysite/plant/templates/plant/upload.html
{% extends "plant/base.html" %}
{% block content %}

<form action="{% url 'plant:upload' %}" method="POST" enctype="multipart/form-data">      
    {% csrf_token %} 
    {{ form }}
    <input type="submit" value="submit" />
</form>

{% for p in photos %}
  {% if forloop.last %}
    {% if p.image %}
      <div>
          <img src="{{ p.image.url }}" style="width:300px;height:auto" />
      </div>
    {% endif %}
  {% endif %}
{% endfor %}
{% endblock %}

workspase/mysite/plant/templates/plant/user_create.html
{% extends "plant/base.html" %}

<!DOCTYPE html>
<html lang="ja">
  <body>
    {% block content %}    
      <form method="POST" action="">
        {% csrf_token %}
        <label>Username</label>
        {{ form.username }}
        {{ form.username.errors }}
        <label>Password</label>
        {{ form.password1 }}
        {{ form.password1.errors }}
        <label>Confirm Password</label>
        {{ form.password2 }}
        {{ form.password2.errors }}
        <button type = "submit">submit</button>
      </form>
    {% endblock %}    
  </body>
</html>

<!-- <form action="" method="POST"> -->
    <!-- {{ form.non_field_errors }}
    {% for field in form %} -->
    <!-- <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">Submit</button> -->
<!-- </form> -->

workspase/mysite/plant/templates/plant/user_create_complete.html
{% extends "plant/base.html" %}
{% block content %}
<p>
    Configuration!!<br>
    Registration is done;)<br>
    <a class="btn btn-primary btn-lg" href="{% url 'plant:login' %}">LOGIN</a>
</p>
{% endblock %}

workspase/mysite/plant/templates/plant/user_create_done.html
{% extends "plant/base.html" %}
{% block content %}
<p>
    We send e-mail. <br>
    Please check and click URL.
</p>
{% endblock %}